config/routes.rb
Metamuna2::Application.routes.draw do
 
  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new'
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => 'home#index'
  devise_for :users
  resources :users, :only => [:show, :index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
	rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    render :layout => false
  end
  
  def help
  end
  
  def about
    render :layout => false

  end
  
  def basic
    render :layout => false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/home_helper.rb
module HomeHelper
	
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
	
end

app/views/home/index.html.erb
<h3>Home</h3>
<% @users.each do |user| %>
  <p>User: <%=link_to user.name, user %></p>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Metamuna2", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>        
    </li>
  <% else %>
    <li>
    <%= link_to 'Login',  new_user_session_path, %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Metamuna" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-bottom">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/static_pages/about.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">
<title>Metamuna</title>
<style type="text/css">
@import url(http://fonts.googleapis.com/css?family=Damion);
</style>
<link href="../stylesheets/style3.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script type="text/javascript" src="http://current.bootstrapcdn.com/bootstrap-v204/js/bootstrap.min.js"></script>
<script type="text/javascript" src="http://twitter.github.com/bootstrap/assets/js/bootstrap-tab.js"></script>
<script type="text/javascript" src="http://twitter.github.com/bootstrap/assets/js/bootstrap-tooltip.js"></script>
<script type="text/javascript" src="http://twitter.github.com/bootstrap/assets/js/bootstrap-popover.js"></script>


<style type="text/css">
#apDiv1 {
	position:absolute;
	width:824px;
	height:309px;
	z-index:1;
	left: 347px;
	top: 203px;
}
#apDiv2 {
	position:absolute;
	width:650px;
	height:115px;
	z-index:2;
	left: 423px;
	top: 358px;
}

#apDiv4 {
	position:absolute;
	width:508px;
	height:42px;
	z-index:2;
	left: 468px;
	top: 358px;
}
#apDiv5 {
	position:absolute;
	width:200px;
	height:115px;
	z-index:1;
	left: 528px;
	top: 157px;
}

body {
	background-image: url(../images/subtle_stripes.png);
	background-repeat: repeat;
}
#gurl {
	position:absolute;
	width:131px;
	height:293px;
	z-index:3;
	left: 361px;
	top: 515px;
}
#dood {
	position:absolute;
	width:122px;
	height:306px;
	z-index:4;
	left: 580px;
	top: 507px;
}
#gurl2 {
	position:absolute;
	width:186px;
	height:301px;
	z-index:5;
	left: 868px;
	top: 512px;
}
</style>


</head>




<body>
<a id="gurl" href="#" rel="popover" data-original-title="Chick:" data-content="Metamune is a virtual swapmeet, in real time"><img src="../images/people.png" width="111" height="299" alt="mmgurl" /></a>
<script>
  $("a[rel=popover]").popover({placement:'top' });

</script>


<a id="gurl2" href="#" rel="popover" data-original-title="Chick:" data-content="Craigslist is so mainstream"><img src="../images/people3.png" width="111" height="299" alt="mmgurl" /></a>
<script>
  $("a[rel=popover]").popover({placement:'top' });

</script>

<div class="wrapper">
  <div id="apDiv3"></div>
<center><h2>Sign up</h2>

<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>
<p><%= f.label :name %><br />
<%= f.text_field :name %></p>

  <div><%= f.label :email %><br />
  <%= f.email_field :email %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>

  <div><%= f.submit "Sign up",:class => 'button pink' %></div>
<% end %>

<%= render "devise/shared/links" %>
</center>

</style>
<center><div id="apDiv1"><img src="../images/metamuna.png" alt="metamune" width="600" height="160" align="middle" /></div></center>


</div>
</div>
<div class="push"></div>
</div>

<a id="dood" href="#" rel="popover" data-original-title="Dude:" data-content="Can I find an Iphone 4S?"><img src="../images/people2.png" width="111" height="306" alt="dood" /></a>
<script>
  $("a[rel=popover]").popover({placement:'right' });

</script>


</body>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
	<title>metamuna</title>
	<%= stylesheet_link_tag    "application", media: "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<style type="text/css">
	@import url(http://fonts.googleapis.com/css?family=Damion);
	</style>
	<link href="../stylesheets/style3.css"rel="stylesheet" type="text/css" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
	<script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-dropdown.js"></script>
	<script src="http://twitter.github.com/bootstrap/assets/js/bootstrap-tab.js"></script>
	<style type="text/css">
	#apDiv1 {
	  position:absolute;
	  width:824px;
	  height:309px;
	  z-index:1;
	  left: 347px;
	  top: 203px;
	}
	#apDiv2 {
	  position:absolute;
	  width:650px;
	  height:115px;
	  z-index:2;
	  left: 423px;
	  top: 358px;
	}

	</style>
  </head>
  <body background="https://dl.dropbox.com/u/6395943/metamunages/13.png" href="../stylesheets/style3.css" rel="stylesheet" type="text/css">
  <div class="wrapper">
  <div id="apDiv3"></div>
  <style> 

  </style>
  <center><div id="apDiv1"><img src="https://dl.dropbox.com/u/6395943/metamunages/metamuna.png" alt="metamuna" width="600" height="160" align="middle" /></div></center>/


  </div>
  </div>


  <div class="well" id="apDiv2">
  <center><p style='padding-top : 35px'></p>
  <form class=" form-inline" ">
  	<input type="text" class="input-small" placeholder="Email" ">
  	<input type="password" class="input-small" placeholder="Password">
  	<label class="checkbox">
  	  <input type="checkbox"> Remember me &nbsp &nbsp </label>
  
  	  <a href="#" class="button pink">AWWWW YEAHHHHH</a>
  	  <a href="#" class="button teal">Let me in</a>
  
    </form></center>
</center>
  </div>
  <div class="push"></div>
  </div>
	  <%= yield %>


	</div>
  </body>
  <div class="navbar navbar-fixed-bottom"style="font-family: 'Lobster', sans-serif;">
	<div class="navbar-inner">

	  <div class="container">
		<ul class="nav pull-right">
	<li class="dropdown ">
	<a href="#" data-toggle="dropdown" class="dropdown-toggle ">Legal<b class="caret up"></b></a>
	<ul class="dropdown-menu dropup-menu" id="menu3">


	  <li><%= link_to "Privacy Policy", about_path %></li>
	  <li><a href="#">Terms of Service</a></li>
	  <li class="divider"></li>
	  <li><a href="#">Do's and Dont's</a></li>

	</ul>
  </li>

  </ul>
		<ul class="nav pull-left">
		  <li class="dropdown">
		  <a href="#" data-toggle="dropdown" style="text-decoration:none" class="dropdown-toggle"><i class="icon-globe"></i>
  <b class="caret up"></b></a>
			   <ul class="dropdown-menu dropup-menu" id="menu3">
				<li><a href="#">Twitter</a></li>
				<li><a href="#">Pinterest</a></li>
				<li><a href="#">Google +</a></li>
				<li class="divider"></li>
	</ul>

		</li>
			<li><a href="#">Help</a></li>
			<li class="dropdown ">
	<a href="#" data-toggle="dropdown" class="dropdown-toggle ">About<b class="caret up"></b></a>
	<ul class="dropdown-menu dropup-menu" id="menu3">
	  <li><%= link_to "Artwork", about_path %></li>
	  <li><%= link_to "Team", about_path %></li>
	  <li><a href="#">Blog</a></li>
	  <li class="divider"></li>
	  <li><%= link_to "What is Metamune?", about_path %></li>
	</ul>
  </li>
			  </li>
  </ul>
	  </ul>

	  </div>
	</div>
  </div>

</html>

app/views/users/index.html.erb
<h3>Users</h3>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>